spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/medicine
spring.datasource.username=root
spring.datasource.password=Ritik@3112

spring.jpa.show.sql = true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
